theme: jekyll-theme-leap-day
title: HayanMind Inc.
description: Towards a multilingual species
show_downloads: false
google_analytics: UA-102556724-1
is_project_page: false # https://help.github.com/articles/repository-metadata-on-github-pages/
